### ISSUE TITLE
establish / structure krievo org to enable collaborative decision deposits

### ISSUE THREAD

**Issue by monsieurbulb** [virto-network/virto-communities#64]
OpenGov proposals require a decision deposit to prevent spamming and ensure a level of financial risk/commitment aligned to each track. 

Currently proposers need to already have KSM or rely on a supporter who can contribute the DD. In some cases the KSM amounts are prohibitive, even more so on Polkadot

- Root requires 3,333 KSM 
- Wish for change 666 KSM

It would be useful to use krievo to enable collaborative decison deposits and democratise access to the tracks - it would also be a good practical demonstration of the capabilities of the infrastructure.

**Comment by olanod** [comment]
Without changing the way pallet referenda works in the relay chain, the only option I see is to do some kind of fundraising within a Kreivo community where members collect KSM to the sovereign account of the community and then the community votes to place the decision deposit for a given referendum. Perhaps the community can come up with an incentive for contributors who transfer their KSM? The difficulty is that said KSM needs to be free, it cannot be locked in voting or staking, so the incentive better be good 😅 

I'll close it for now since there's no actionable items for Virto that we could implement other than allowing communities deploy contracts to create the incentive mechanism.
