### ISSUE TITLE
When you add members on an iniciative the Wallet input adds strangely

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#74]
We have this:

![image](https://github.com/user-attachments/assets/954cd15d-1ad5-4769-8ac9-ac0e191c819e)

But shouldn't we just have this:

![image](https://github.com/user-attachments/assets/782c7611-9f61-43ed-b505-a6694a2b95df)

If you click on the last "+" button it adds inputs constantly, till you have something like this:

![image](https://github.com/user-attachments/assets/ae04ce61-5287-4bd6-8ab1-4826fa6c66aa)

**Comment by b-avb** [comment]
For now there is no problem because a "flatmap" is made of the `AddMembersAction` to extract the addresses that need to be invited.

I have tried to provide the same ergonomics that polkadotjs allows by adding different actions. I see it like this so that batch actions are done in the future, where the _first_ added members can be sorted for members with rank **X** and the _second_ or _n_ batch can be sorted with members with rank **Y**.

**Comment by ail3ngrimaldi** [comment]
Closed due to lack of information when creating the issue + its being somehow solved on #147
